version: '3.7'
services:

  ravendb:
    image: ravendb/ravendb:ubuntu-latest
    container_name: raven-db
    hostname: raven-db
    ports:
      - 8088:8080
      - 38888:38888
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
    volumes:
      - .ravendb/volumes:/opt/RavenDB/Server/RavenData
    networks:
      - raven-network

networks:
  raven-network:
    driver: bridge
